{{- if .Values.services.core.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "asd.fullname" . }}-core
  labels:
    app.kubernetes.io/name: {{ include "asd.fullname" . }}
    app.kubernetes.io/component: core
spec:
  replicas: {{ .Values.services.core.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "asd.fullname" . }}
      app.kubernetes.io/component: core
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "asd.fullname" . }}
        app.kubernetes.io/component: core
    spec:
      imagePullSecrets: {{ toYaml .Values.global.imagePullSecrets | nindent 6 }}
      containers:
        - name: core
          image: {{ .Values.services.core.image | quote }}
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          ports:
            - containerPort: {{ .Values.services.core.containerPort | default 8080 }}
          env: {{ toYaml .Values.services.core.env | nindent 12 }}
          resources: {{ toYaml .Values.services.core.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "asd.fullname" . }}-core
  labels:
    app.kubernetes.io/name: {{ include "asd.fullname" . }}
    app.kubernetes.io/component: core
spec:
  type: {{ .Values.services.core.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: {{ include "asd.fullname" . }}
    app.kubernetes.io/component: core
  ports:
    - name: http
      port: {{ .Values.services.core.service.port | default 80 }}
      targetPort: {{ .Values.services.core.containerPort | default 8080 }}
{{- end }}
