[package]
name = "tarpit-rs"
version = "0.1.0"
edition = "2021"
rust-version = "1.78"

[lib]
name = "tarpit_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24.2", features = ["extension-module"] }
postgres = "0.19"
rand = "0.8"
html-escape = "0.2"
