services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI
    networks:
      - defense_network
    restart: unless-stopped

  mock_external_api:
    image: stoplight/prism:4
    container_name: mock_external_api
    command: mock -h 0.0.0.0 /mocks/external_api.yaml
    volumes:
      - ./mocks/external_api.yaml:/mocks/external_api.yaml:ro
    ports:
      - "8000:8000"
    networks:
      - defense_network
    restart: unless-stopped

  mock_ip_reputation_api:
    image: stoplight/prism:4
    container_name: mock_ip_reputation_api
    command: mock -h 0.0.0.0 /mocks/ip_reputation_api.yaml
    volumes:
      - ./mocks/ip_reputation_api.yaml:/mocks/ip_reputation_api.yaml:ro
    ports:
      - "8001:8000"
    networks:
      - defense_network
    restart: unless-stopped

  mock_community_blocklist_api:
    image: stoplight/prism:4
    container_name: mock_community_blocklist_api
    command: mock -h 0.0.0.0 /mocks/community_blocklist_api.yaml
    volumes:
      - ./mocks/community_blocklist_api.yaml:/mocks/community_blocklist_api.yaml:ro
    ports:
      - "8002:8000"
    networks:
      - defense_network
    restart: unless-stopped

  ai_service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ALERT_SMTP_HOST=mailhog
      - ALERT_SMTP_PORT=1025
      - ALERT_SMTP_USE_TLS=false
      - ALERT_SMTP_USER=
      - ALERT_SMTP_PASSWORD_FILE=/run/secrets/smtp_password.txt
      - USE_MOCK_EXTERNAL_API=true
      - EXTERNAL_API_URL=http://mock_external_api:8000
      - IP_REPUTATION_API_URL=http://mock_ip_reputation_api:8000
      - COMMUNITY_BLOCKLIST_API_URL=http://mock_community_blocklist_api:8000
    networks:
      - defense_network
    restart: unless-stopped

  escalation_engine:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ALERT_SMTP_HOST=mailhog
      - ALERT_SMTP_PORT=1025
      - ALERT_SMTP_USE_TLS=false
      - ALERT_SMTP_USER=
      - ALERT_SMTP_PASSWORD_FILE=/run/secrets/smtp_password.txt
      - USE_MOCK_EXTERNAL_API=true
      - EXTERNAL_API_URL=http://mock_external_api:8000
      - IP_REPUTATION_API_URL=http://mock_ip_reputation_api:8000
      - COMMUNITY_BLOCKLIST_API_URL=http://mock_community_blocklist_api:8000
    networks:
      - defense_network
    restart: unless-stopped

  tarpit_api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ALERT_SMTP_HOST=mailhog
      - ALERT_SMTP_PORT=1025
      - ALERT_SMTP_USE_TLS=false
      - ALERT_SMTP_USER=
      - ALERT_SMTP_PASSWORD_FILE=/run/secrets/smtp_password.txt
      - USE_MOCK_EXTERNAL_API=true
      - EXTERNAL_API_URL=http://mock_external_api:8000
      - IP_REPUTATION_API_URL=http://mock_ip_reputation_api:8000
      - COMMUNITY_BLOCKLIST_API_URL=http://mock_community_blocklist_api:8000
    networks:
      - defense_network
    restart: unless-stopped

networks:
  defense_network:
    driver: bridge
