services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "${ALERT_SMTP_PORT}:1025"
      - "${ALERT_SMTP_WEB_PORT}:8025"
    networks:
      - defense_network
    restart: unless-stopped

  mock_external_api:
    image: stoplight/prism:4
    container_name: mock_external_api
    command: mock -h 0.0.0.0 /mocks/external_api.yaml
    volumes:
      - ./mocks/external_api.yaml:/mocks/external_api.yaml:ro
    ports:
      - "${MOCK_EXTERNAL_API_PORT}:8000"
    networks:
      - defense_network
    restart: unless-stopped

  mock_ip_reputation_api:
    image: stoplight/prism:4
    container_name: mock_ip_reputation_api
    command: mock -h 0.0.0.0 /mocks/ip_reputation_api.yaml
    volumes:
      - ./mocks/ip_reputation_api.yaml:/mocks/ip_reputation_api.yaml:ro
    ports:
      - "${MOCK_IP_REPUTATION_PORT}:8000"
    networks:
      - defense_network
    restart: unless-stopped

  mock_community_blocklist_api:
    image: stoplight/prism:4
    container_name: mock_community_blocklist_api
    command: mock -h 0.0.0.0 /mocks/community_blocklist_api.yaml
    volumes:
      - ./mocks/community_blocklist_api.yaml:/mocks/community_blocklist_api.yaml:ro
    ports:
      - "${MOCK_BLOCKLIST_API_PORT}:8000"
    networks:
      - defense_network
    restart: unless-stopped

  nginx_proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_proxy
    user: nobody
    entrypoint: []
    command: ["/usr/local/openresty/nginx/sbin/nginx", "-g", "daemon off;"]
    ports:
      - "${NGINX_HTTP_PORT:-8080}:80"
      - "${NGINX_HTTPS_PORT:-8443}:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/lua:/etc/nginx/lua:ro
      - ./config/robots.txt:/etc/nginx/robots.txt:ro
      - ./docs:/var/www/html/docs:ro
      - ./archives:/usr/share/nginx/html/archives:ro
      - ./logs/nginx:/var/log/nginx
      - ./certs:/etc/nginx/certs:ro
      - ./secrets/.htpasswd:/etc/nginx/secrets/.htpasswd:ro
      - nginx_client_body_temp:/var/run/openresty/nginx-client-body
      - nginx_proxy_temp:/var/cache/nginx/proxy_temp
      - nginx_fastcgi_temp:/var/cache/nginx/fastcgi_temp
      - nginx_uwsgi_temp:/var/cache/nginx/uwsgi_temp
      - nginx_scgi_temp:/var/cache/nginx/scgi_temp
    depends_on:
      tarpit_api:
        condition: service_healthy
      escalation_engine:
        condition: service_healthy
      admin_ui:
        condition: service_healthy
      ai_service:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB_BLOCKLIST=2
      - REAL_BACKEND_HOST=${REAL_BACKEND_HOST:-http://your-real-app-service:8080}
      - LUA_PATH=/usr/local/openresty/lualib/?.lua;/usr/local/openresty/nginx/lua/?.lua;/etc/nginx/lua/?.lua;;
      - LUA_CPATH=/usr/local/openresty/lualib/?.so;;
      - AI_SERVICE_PORT=${AI_SERVICE_PORT}
      - ESCALATION_ENGINE_PORT=${ESCALATION_ENGINE_PORT}
      - TARPIT_API_PORT=${TARPIT_API_PORT}
      - ADMIN_UI_PORT=${ADMIN_UI_PORT}
    networks:
      - defense_network
    secrets:
      - redis_password
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  ai_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_service
    working_dir: /app
    entrypoint: []
    command: [
      "uvicorn",
      "ai_service.ai_webhook:app",
      "--host", "0.0.0.0",
      "--port", "${AI_SERVICE_PORT}",
      "--workers", "${UVICORN_WORKERS:-2}",
      "--log-level", "${UVICORN_LOG_LEVEL:-info}"
    ]
    environment:
      - PYTHONPATH=/app
      - ALERT_SMTP_HOST=${ALERT_SMTP_HOST}
      - ALERT_SMTP_PORT=${ALERT_SMTP_PORT}
      - ALERT_SMTP_USE_TLS=${ALERT_SMTP_USE_TLS}
      - LOG_LEVEL=${LOG_LEVEL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - AI_SERVICE_PORT=${AI_SERVICE_PORT}
      - DEBUG=${DEBUG}
      - APP_ENV=${APP_ENV}
    volumes:
      - ./ai_service:/app/ai_service
      - ./shared:/app/shared
      - ./metrics.py:/app/metrics.py:ro
      - ./logs:/app/logs
      - ./data:/app/data
      - ./util:/app/util
    secrets:
      - smtp_password
      - community_blocklist_api_key
      - redis_password
    depends_on:
      redis:
        condition: service_healthy
      mailhog:
        condition: service_started
    networks:
      - defense_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${AI_SERVICE_PORT}/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  escalation_engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: escalation_engine
    working_dir: /app
    entrypoint: []
    command: [
      "uvicorn",
      "escalation.escalation_engine:app",
      "--host", "0.0.0.0",
      "--port", "${ESCALATION_ENGINE_PORT}",
      "--workers", "${UVICORN_WORKERS:-2}",
      "--log-level", "${UVICORN_LOG_LEVEL:-info}"
    ]
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=${LOG_LEVEL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - ESCALATION_ENGINE_PORT=${ESCALATION_ENGINE_PORT}
      - ESCALATION_THRESHOLD=${ESCALATION_THRESHOLD}
      - EXTERNAL_API_URL=${EXTERNAL_API_URL}
      - IP_REPUTATION_API_URL=${IP_REPUTATION_API_URL}
      - DEBUG=${DEBUG}
      - APP_ENV=${APP_ENV}
    volumes:
      - ./escalation:/app/escalation
      - ./shared:/app/shared
      - ./metrics.py:/app/metrics.py:ro
      - ./models:/app/models:ro
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - ./data:/app/data
      - ./util:/app/util
    secrets:
      - external_api_key
      - ip_reputation_api_key
      - redis_password
    depends_on:
      ai_service:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - defense_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${ESCALATION_ENGINE_PORT}/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

  tarpit_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tarpit_api
    working_dir: /app
    entrypoint: []
    command: [
      "uvicorn",
      "tarpit.tarpit_api:app",
      "--host", "0.0.0.0",
      "--port", "${TARPIT_API_PORT}",
      "--workers", "${UVICORN_WORKERS:-2}",
      "--log-level", "${UVICORN_LOG_LEVEL:-info}"
    ]
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=${LOG_LEVEL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - TARPIT_API_PORT=${TARPIT_API_PORT}
      - DEBUG=${DEBUG}
      - APP_ENV=${APP_ENV}
    volumes:
      - ./tarpit:/app/tarpit
      - ./shared:/app/shared
      - ./metrics.py:/app/metrics.py:ro
      - ./logs:/app/logs
      - ./data:/app/data
      - ./util:/app/util
    secrets:
      - pg_password
      - redis_password
      - system_seed
    depends_on:
      escalation_engine:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - defense_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${TARPIT_API_PORT}/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  admin_ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: admin_ui
    working_dir: /app
    entrypoint: []
    command: ["python", "admin_ui/admin_ui.py"]
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=${FLASK_ENV}
      - ADMIN_UI_PORT=${ADMIN_UI_PORT}
      - DEBUG=${DEBUG}
      - APP_ENV=${APP_ENV}
      - ADMIN_UI_USERNAME=${ADMIN_UI_USERNAME}
    volumes:
      - ./admin_ui:/app/admin_ui
      - ./shared:/app/shared
      - ./metrics.py:/app/metrics.py:ro
      - ./logs:/app/logs
    secrets:
      - admin_ui_password
    networks:
      - defense_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${ADMIN_UI_PORT}/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  archive_rotator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: archive_rotator
    working_dir: /app
    entrypoint: []
    command: ["python", "tarpit/rotating_archive.py"]
    environment:
      - PYTHONPATH=/app
      - DEFAULT_ARCHIVE_DIR=/app/fake_archives
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./tarpit:/app/tarpit
      - ./archives:/app/fake_archives
      - ./logs:/app/logs
    networks:
      - defense_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis_store
    volumes:
      - redis_data:/data
    networks:
      - defense_network
    restart: unless-stopped
    command: >
      sh -c 'if [ -f /run/secrets/redis_password.txt ] && [ -s /run/secrets/redis_password.txt ]; then \
               echo "Starting Redis with password protection."; \
               exec redis-server --save 60 1 --loglevel warning --requirepass "$(cat /run/secrets/redis_password.txt)"; \
             else \
               echo "Starting Redis without password protection (password file not found or empty)."; \
               exec redis-server --save 60 1 --loglevel warning; \
             fi'
    secrets:
      - source: redis_password
        target: /run/secrets/redis_password.txt
        mode: 0400
    healthcheck:
      test: >
        sh -c 'if [ -f /run/secrets/redis_password.txt ] && [ -s /run/secrets/redis_password.txt ]; then \
                 redis-cli -a "$(cat /run/secrets/redis_password.txt)" ping | grep -q PONG; \
               else \
                 redis-cli ping | grep -q PONG; \
               fi'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  postgres:
    image: postgres:15-alpine
    container_name: postgres_markov_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init_markov.sql:/docker-entrypoint-initdb.d/init_markov.sql:ro
    environment:
      - POSTGRES_DB=${PG_DBNAME:-markovdb}
      - POSTGRES_USER=${PG_USER:-markovuser}
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg_password.txt
    secrets:
      - source: pg_password
        target: /run/secrets/pg_password.txt
    networks:
      - defense_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-markovuser} -d ${POSTGRES_DB:-markovdb} -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  corpus_updater:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: corpus_updater
    working_dir: /app
    entrypoint: []
    command: ["python", "util/corpus_wikipedia_updater.py"]
    environment:
      - PYTHONPATH=/app
      - WIKIPEDIA_CORPUS_FILE=${WIKIPEDIA_CORPUS_FILE}
      - WIKIPEDIA_NUM_ARTICLES=${WIKIPEDIA_NUM_ARTICLES:-5}
      - WIKIPEDIA_LANGUAGE=${WIKIPEDIA_LANGUAGE:-en}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./util:/app/util
      - ./data:/app/data
    networks:
      - defense_network

  robots_fetcher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: robots_fetcher
    working_dir: /app
    entrypoint: []
    command: ["python", "util/robots_fetcher.py"]
    environment:
      - PYTHONPATH=/app
      - REAL_BACKEND_HOST=${REAL_BACKEND_HOST_FOR_ROBOTS:-http://your-real-app-service:8080}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./util:/app/util
    networks:
      - defense_network

  markov_trainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: markov_trainer
    working_dir: /app
    entrypoint: []
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./rag:/app/rag
      - ./data:/app/data
    secrets:
      - pg_password
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - defense_network

  model_trainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: model_trainer
    working_dir: /app
    entrypoint: []
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./rag:/app/rag
      - ./shared:/app/shared
      - ./metrics.py:/app/metrics.py:ro
      - ./models:/app/models
      - ./data:/app/data
      - ./config:/app/config
      - ./logs:/app/logs
    secrets:
      - training_pg_password
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - defense_network

networks:
  defense_network:
    driver: bridge

volumes:
  nginx_client_body_temp:
  nginx_proxy_temp:
  nginx_fastcgi_temp:
  nginx_uwsgi_temp:
  nginx_scgi_temp:
  redis_data:
  postgres_data:

secrets:
  smtp_password:
    file: ./secrets/smtp_password.txt
  external_api_key:
    file: ./secrets/external_api_key.txt
  ip_reputation_api_key:
    file: ./secrets/ip_reputation_api_key.txt
  community_blocklist_api_key:
    file: ./secrets/community_blocklist_api_key.txt
  pg_password:
    file: ./secrets/pg_password.txt
  redis_password:
    file: ./secrets/redis_password.txt
  system_seed:
    file: ./secrets/system_seed.txt
  training_pg_password:
    file: ./secrets/training_pg_password.txt
  admin_ui_password:
    file: ./secrets/admin_ui_password.txt