"""Metrics interface for the AI service."""

from src.shared.metrics import (  # noqa: F401
    COMMUNITY_REPORTS_ATTEMPTED,
    COMMUNITY_REPORTS_ERRORS_REQUEST,
    COMMUNITY_REPORTS_ERRORS_RESPONSE_DECODE,
    COMMUNITY_REPORTS_ERRORS_STATUS,
    COMMUNITY_REPORTS_ERRORS_TIMEOUT,
    COMMUNITY_REPORTS_ERRORS_UNEXPECTED,
    COMMUNITY_REPORTS_SUCCESS,
    SECURITY_ANOMALIES_DETECTED,
    SECURITY_ATTACKS_BLOCKED,
    SECURITY_HONEYPOT_HITS,
    SECURITY_IP_BLOCKS,
    SECURITY_RATE_LIMIT_VIOLATIONS,
    SECURITY_SUSPICIOUS_PATTERNS,
    SECURITY_THREATS_DETECTED,
    SECURITY_WAF_RULES_TRIGGERED,
    increment_counter_metric,
)

__all__ = [name for name in locals() if not name.startswith("_")]
