"""Metrics interface for the AI service."""

from src.shared.metrics import (
    COMMUNITY_REPORTS_ATTEMPTED,
    COMMUNITY_REPORTS_ERRORS_REQUEST,
    COMMUNITY_REPORTS_ERRORS_RESPONSE_DECODE,
    COMMUNITY_REPORTS_ERRORS_STATUS,
    COMMUNITY_REPORTS_ERRORS_TIMEOUT,
    COMMUNITY_REPORTS_ERRORS_UNEXPECTED,
    COMMUNITY_REPORTS_SUCCESS,
    increment_counter_metric,
)

__all__ = [
    "COMMUNITY_REPORTS_ATTEMPTED",
    "COMMUNITY_REPORTS_ERRORS_REQUEST",
    "COMMUNITY_REPORTS_ERRORS_RESPONSE_DECODE",
    "COMMUNITY_REPORTS_ERRORS_STATUS",
    "COMMUNITY_REPORTS_ERRORS_TIMEOUT",
    "COMMUNITY_REPORTS_ERRORS_UNEXPECTED",
    "COMMUNITY_REPORTS_SUCCESS",
    "increment_counter_metric",
]
