#!/bin/sh
set -eu

OUTPUT_PATH="${1:-/etc/nginx/generated-conf/20-cdn-origin-lockdown.conf}"
HTTPS_OUTPUT_PATH="${2:-$(dirname "$OUTPUT_PATH")/30-https-server.conf}"
LOCKDOWN_ENABLED="${SECURITY_CDN_ORIGIN_LOCKDOWN:-false}"
TRUSTED_CIDRS="${SECURITY_CDN_TRUSTED_PROXY_CIDRS:-}"

is_truthy() {
  case "$(printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]')" in
    1|true|yes|on) return 0 ;;
    *) return 1 ;;
  esac
}

trim_whitespace() {
  value=${1:-}
  value=${value#"${value%%[![:space:]]*}"}
  value=${value%"${value##*[![:space:]]}"}
  printf '%s' "$value"
}

normalize_cidr() {
  value=$(trim_whitespace "${1:-}")

  if [ -z "$value" ]; then
    return 1
  fi

  case "$value" in
    *[!0-9A-Fa-f:./]*|*/*/*)
      return 1
      ;;
  esac

  prefix=${value#*/}
  if [ "$prefix" != "$value" ]; then
    address=${value%/*}
    case "$prefix" in
      ''|*[!0-9]*)
        return 1
        ;;
    esac
    if [ "$prefix" -gt 128 ]; then
      return 1
    fi
  else
    address=$value
  fi

  if [ -z "$address" ]; then
    return 1
  fi

  printf '%s' "$value"
}

{
  echo "# Generated by render_cdn_origin_lockdown.sh"
  echo "# Restore the originating client address only for explicitly trusted CDN peers."
  OLD_IFS=${IFS}
  IFS=','
  for cidr in $TRUSTED_CIDRS; do
    trimmed=$(normalize_cidr "$cidr") || {
      printf >&2 'Invalid SECURITY_CDN_TRUSTED_PROXY_CIDRS entry: %s\n' "$cidr"
      exit 1
    }
    if [ -n "$trimmed" ]; then
      echo "set_real_ip_from $trimmed;"
    fi
  done
  IFS=${OLD_IFS}

  if [ -n "$(trim_whitespace "$TRUSTED_CIDRS")" ]; then
    echo "real_ip_header CF-Connecting-IP;"
    echo "real_ip_recursive on;"
  else
    echo "# No trusted CDN CIDRs configured; forwarded client-IP headers are ignored."
  fi

  if is_truthy "$LOCKDOWN_ENABLED"; then
    echo "# Allow local container health checks even when CDN origin lockdown is enabled."
    echo "allow 127.0.0.1/32;"
    echo "allow ::1/128;"
    OLD_IFS=${IFS}
    IFS=','
    for cidr in $TRUSTED_CIDRS; do
      trimmed=$(normalize_cidr "$cidr") || exit 1
      echo "allow $trimmed;"
    done
    IFS=${OLD_IFS}
    echo "deny all;"
  else
    echo "# CDN origin lockdown is disabled for this runtime."
  fi
} >"$OUTPUT_PATH"

if is_truthy "${ENABLE_HTTPS:-false}"; then
  CERT_PATH="${TLS_CERT_PATH:-/etc/nginx/certs/tls.crt}"
  KEY_PATH="${TLS_KEY_PATH:-/etc/nginx/certs/tls.key}"
  if [ ! -r "$CERT_PATH" ] || [ ! -r "$KEY_PATH" ]; then
    printf >&2 'ENABLE_HTTPS is true but TLS certificate or key is not readable.\n'
    exit 1
  fi
  case "$CERT_PATH$KEY_PATH" in
    *[!0-9A-Za-z_./:-]*)
      printf >&2 'TLS certificate paths contain unsupported characters.\n'
      exit 1
      ;;
  esac
  cat >"$HTTPS_OUTPUT_PATH" <<EOF
# Generated by render_cdn_origin_lockdown.sh
server {
    listen 443 ssl;
    server_name _;
    ssl_certificate $CERT_PATH;
    ssl_certificate_key $KEY_PATH;
    ssl_protocols TLSv1.2 TLSv1.3;
    root /usr/share/nginx/html/docs_ui;
    index welcome.html;
    location = /healthz { access_log off; return 200 "ok\\n"; }
    location / { try_files \$uri \$uri/ =404; limit_req zone=global_limit burst=60 nodelay; }
}
EOF
else
  cat >"$HTTPS_OUTPUT_PATH" <<'EOF'
# Generated by render_cdn_origin_lockdown.sh
# HTTPS listener disabled. Terminate TLS upstream or set ENABLE_HTTPS=true with readable certificates.
EOF
fi
