#!/bin/sh
set -eu

OUTPUT_PATH="${1:-/etc/nginx/conf.d/20-cdn-origin-lockdown.conf}"
LOCKDOWN_ENABLED="${SECURITY_CDN_ORIGIN_LOCKDOWN:-false}"
REQUIRE_CLOUDFLARE_ACCOUNT="${REQUIRE_CLOUDFLARE_ACCOUNT:-false}"
TRUSTED_CIDRS="${SECURITY_CDN_TRUSTED_PROXY_CIDRS:-}"

is_truthy() {
  case "$(printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]')" in
    1|true|yes|on) return 0 ;;
    *) return 1 ;;
  esac
}

write_disabled_file() {
  cat >"$OUTPUT_PATH" <<'EOF'
# Generated by render_cdn_origin_lockdown.sh
# CDN origin lockdown is disabled for this runtime.
EOF
}

if ! is_truthy "$LOCKDOWN_ENABLED" && ! is_truthy "$REQUIRE_CLOUDFLARE_ACCOUNT"; then
  write_disabled_file
  exit 0
fi

is_valid_cidr() {
  # Accept only characters legal in an IPv4/IPv6 CIDR: digits, hex letters,
  # colons, dots, and an optional trailing slash with a 1-3 digit prefix length
  # (0-128 covers both IPv4/32 and IPv6/128).  Any other character
  # (semicolons, braces, whitespace, newlines …) would allow nginx-config
  # injection and is therefore rejected.  Nginx itself enforces correct
  # prefix-length semantics at startup.
  printf '%s' "$1" | grep -qE '^[0-9a-fA-F:.]+(/([0-9]|[1-9][0-9]|1[01][0-9]|12[0-8]))?$'
}

{
  echo "# Generated by render_cdn_origin_lockdown.sh"
  echo "# Allow local container health checks even when CDN origin lockdown is enabled."
  echo "allow 127.0.0.1/32;"
  echo "allow ::1/128;"
  OLD_IFS=${IFS}
  IFS=','
  for cidr in $TRUSTED_CIDRS; do
    # Strip all whitespace (including CR/LF) before validating.
    trimmed=$(printf '%s' "$cidr" | tr -d '[:space:]')
    if [ -n "$trimmed" ]; then
      if ! is_valid_cidr "$trimmed"; then
        printf 'render_cdn_origin_lockdown.sh: invalid CIDR rejected: %s\n' "$trimmed" >&2
        exit 1
      fi
      echo "allow $trimmed;"
    fi
  done
  IFS=${OLD_IFS}
  echo "deny all;"
} >"$OUTPUT_PATH"
