# kubernetes/ai-service-deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: ai-defense
spec:
  selector:
    app: ai-service
  ports:
  - name: http
    port: 8000
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  namespace: ai-defense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
      - name: ai-service
        image: your-registry/ai-scraping-defense:latest
        imagePullPolicy: Always
        # Updated command to run the Uvicorn server for the AI webhook.
        command: ["uvicorn", "src.ai_service.ai_webhook:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
