# kubernetes/archives-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archives-pvc
  namespace: ai-defense # Ensure this is in the correct namespace
spec:
  accessModes:
    - ReadWriteOnce # The archive-rotator writes, Nginx reads.
                    # For Docker Desktop K8s, RWO is generally fine for this scenario.
  resources:
    requests:
      storage: 500Mi # Adjust size as needed for your archives
  # storageClassName: "your-storage-class" # Optional
