# kubernetes/archives-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archives-pvc
  namespace: ai-defense
spec:
  accessModes:
    - ReadWriteOnce # This PVC can be mounted as read-write by a single pod
  resources:
    requests:
      storage: 1Gi # Request 1 Gi