# kubernetes/archives-pvc.yaml
# Requests persistent storage for the tarpit's rotating archive files.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archives-pvc
  namespace: ai-defense
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
