# kubernetes/archive-rotator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archive-rotator
  namespace: ai-defense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archive-rotator
  template:
    metadata:
      labels:
        app: archive-rotator
    spec:
      containers:
      - name: archive-rotator
        image: your-registry/ai-scraping-defense:latest
        # Updated command to run the rotating archive script.
        command: ["python", "src/tarpit/rotating_archive.py"]
        env:
        - name: ARCHIVE_DIR
          value: "/app/archives"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
        - name: archives-storage
          mountPath: /app/archives
      volumes:
      - name: archives-storage
        persistentVolumeClaim:
          claimName: archives-pvc
