# kubernetes/configmap.yaml
# Provides non-sensitive configuration data to the application's services.
# This includes internal service names, ports, and other environment settings.
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ai-defense
data:
  # General application settings
  LOG_LEVEL: "INFO"
  APP_ENV: "production"

  # Internal service hostnames and ports used for pod communication
  AI_SERVICE_HOST: "ai-service"
  AI_SERVICE_PORT: "8000"
  ESCALATION_ENGINE_HOST: "escalation-engine"
  ESCALATION_ENGINE_PORT: "8003"
  TARPIT_API_HOST: "tarpit-api"
  TARPIT_API_PORT: "8001"
  ADMIN_UI_HOST: "admin-ui"
  ADMIN_UI_PORT: "5002"

  # Redis connection details
  REDIS_HOST: "redis" # The service name of the Redis statefulset
  REDIS_PORT: "6379"

  # PostgreSQL connection details
  PG_HOST: "postgres" # The service name of the Postgres statefulset
  PG_PORT: "5432"
