# kubernetes/configmap.yaml
# Provides non-sensitive configuration data to the application's services.
# This includes internal service names, ports, and other environment settings.
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ai-defense
data:
  # General application settings
  LOG_LEVEL: "INFO"
  APP_ENV: "production"

  # Internal service URLs used for communication between pods
  ESCALATION_ENGINE_URL: "http://escalation-engine:8003/escalate"
  ADMIN_UI_URL: "http://admin-ui:5002"
  TARPIT_API_URL: "http://tarpit-api:8001"
  AI_SERVICE_URL: "http://ai-service:8000"

  # Redis connection details
  REDIS_HOST: "redis" # The service name of the Redis statefulset
  REDIS_PORT: "6379"

  # PostgreSQL connection details
  PG_HOST: "postgres" # The service name of the Postgres statefulset
  PG_PORT: "5432"
