# kubernetes/corpus-pvc.yaml
# Requests persistent storage for the text corpus used for model training.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: corpus-data-pvc
  namespace: ai-defense
spec:
  # ReadWriteMany allows the volume to be mounted as read-write by many Nodes.
  # This is useful if the updater and trainer jobs run on different nodes.
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
