# kubernetes/models-pvc.yaml
# Requests persistent storage for the trained machine learning models.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: ai-defense
spec:
  # ReadWriteOnce means the volume can be mounted as read-write by a single Node.
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # Request 5 GiB of storage.
      storage: 5Gi
