# kubernetes/postgres-init-script-cm.yaml
# This ConfigMap holds the SQL script that PostgreSQL will run on its first startup.
# It's used to create the initial database schema.
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: ai-defense
data:
  init.sql: |
    -- This script creates the table for the Markov model if it doesn't already exist.
    CREATE TABLE IF NOT EXISTS markov_model (
        id SERIAL PRIMARY KEY,
        state_key TEXT UNIQUE NOT NULL,
        next_words TEXT NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
