# kubernetes/robots-fetcher-cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: robots-fetcher
  namespace: ai-defense
spec:
  # Runs daily at 1 AM.
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          # This job requires special permissions to edit ConfigMaps,
          # so it needs a dedicated ServiceAccount.
          serviceAccountName: configmap-editor-sa
          containers:
          - name: robots-fetcher
            image: your-registry/ai-scraping-defense:latest
            # Updated command to run the robots fetcher script.
            command: ["python", "src/util/robots_fetcher.py"]
            env:
            - name: REAL_BACKEND_HOST
              value: "http://nginx-proxy.ai-defense.svc.cluster.local"
            - name: ROBOTS_CONFIGMAP_NAME
              # Must match the ConfigMap consumed by the Nginx deployment.
              value: "live-robots-txt-config"
            # The script needs to know its own namespace to patch the ConfigMap.
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          restartPolicy: OnFailure
