# kubernetes/secrets.yaml
# Defines Kubernetes Secrets for sensitive configuration.
# IMPORTANT: Replace placeholder values with your actual base64-encoded secrets.

apiVersion: v1
kind: Secret
metadata:
  name: smtp-credentials
  namespace: ai-defense # Added namespace
type: Opaque
data:
  smtp_password: WU9VUl9TTVRQX1BBU1NXT1JEX0hFUkU= # echo -n 'YOUR_SMTP_PASSWORD_HERE' | base64

---
apiVersion: v1
kind: Secret
metadata:
  name: external-api-credentials
  namespace: ai-defense # Added namespace
type: Opaque
data:
  external_api_key: WU9VUl9FWFRFUk5BTF9BUElfS0VZX0hFUkU= # echo -n 'YOUR_EXTERNAL_API_KEY_HERE' | base64

---
apiVersion: v1
kind: Secret
metadata:
  name: ip-reputation-credentials
  namespace: ai-defense # Added namespace
type: Opaque
data:
  ip_reputation_api_key: WU9VUl9JUF9SRVBVVEFUSU9OX0FQSV9LRVlfSEVSRQ== # echo -n 'YOUR_IP_REPUTATION_API_KEY_HERE' | base64

---
apiVersion: v1
kind: Secret
metadata:
  name: community-blocklist-credentials
  namespace: ai-defense # Added namespace
type: Opaque
data:
  community_blocklist_api_key: WU9VUl9DT01NVU5JVFlfQkxPQ0tMSVNUX0FQSV9LRVlfSEVSRQ== # echo -n 'YOUR_COMMUNITY_BLOCKLIST_API_KEY_HERE' | base64

---
# Secret for PostgreSQL password
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials # Name referenced by postgres-statefulset.yaml and markov-trainer-cronjob.yaml
  namespace: ai-defense # Added namespace
type: Opaque
data:
  # Key name matches what the app expects (e.g., pg_password.txt if mounted as a file)
  # Or just 'password' if read directly as an env var from secretKeyRef
  pg_password.txt: WU9VUl9TRUNVUkVfUEdEX1BBU1NXT1JEX0hFUkU= # echo -n 'your_secure_pg_password' | base64

---
# Optional: Secret for Redis password
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: ai-defense # Added namespace
type: Opaque
data:
  redis_password.txt: WU9VUl9TRUNVUkVfUkVESVNfUEFTU1dPUkRfSEVSRQ== # echo -n 'your_secure_redis_password' | base64
  # If Redis server itself needs 'requirepass', you'd also have a 'password' key here.
  # password: WU9VUl9TRUNVUkVfUkVESVNfUEFTU1dPUkRfSEVSRQ==
