services:
  escalation_engine:
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./scripts/linux/docker-entrypoint.sh:/app/docker-entrypoint.sh
      - ./secrets:/run/secrets:ro

  tarpit_api:
    volumes:
      - ./archives:/app/archives
      - ./scripts/linux/docker-entrypoint.sh:/app/docker-entrypoint.sh
      - ./secrets:/run/secrets:ro

  admin_ui:
    volumes:
      - ./logs:/app/logs
      - ./scripts/linux/docker-entrypoint.sh:/app/docker-entrypoint.sh
      - ./secrets:/run/secrets:ro

  cloud_proxy:
    volumes:
      - ./secrets:/run/secrets:ro

  prompt_router:
    volumes:
      - ./secrets:/run/secrets:ro
