import json
import os
import subprocess
import sqlite3
import re

# Configuration
DB_FILE = "problem_file_map.db"
JSON_FILE = "problem_file_map.json"

def fetch_recent_prs(limit=100):
    print(f"Fetching last {limit} PRs...")
    cmd = [
        "gh", "pr", "list", 
        "--state", "all", 
        "--json", "number,title,body,createdAt", 
        "--limit", str(limit),
        "--author", "@me"
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        return json.loads(result.stdout)
    except subprocess.CalledProcessError as e:
        print(f"Failed to fetch PRs: {e}")
        return []

def extract_issue_number(body):
    # Look for "Fixes #123" or similar
    match = re.search(r"Fixes #(\d+)", body, re.IGNORECASE)
    if match:
        return int(match.group(1))
    return None

def update_db(issue_number, pr_number):
    try:
        conn = sqlite3.connect(DB_FILE)
        cursor = conn.cursor()
        
        # Check if we have this issue
        cursor.execute("SELECT title, pr_created, pr_number FROM problems WHERE pr_number = ? OR pr_number IS NULL", (pr_number,))
        # Actually we want to find the problem by issue number, but our DB doesn't store issue number directly in a dedicated column easily searchable unless we parse titles or something?
        # Wait, the DB schema has: category, severity, confidence, fix_prompt, pr_created, pr_number. It DOES NOT have issue_number.
        # But the title is unique.
        # The script `create_pr_from_issue.py` uses `update_pr_tracking(title, pr_number)`.
        # We need to map Issue Number -> Title.
        # We can't easily do that from the DB alone if we don't have issue_number stored.
        # BUT, we can use the JSON file which keys by Title.
        # OR we can search the DB by title if we knew it.
        
        # Strategy:
        # 1. We have PR body which says "Problem: <Title>"
        # 2. We can extract Title from PR body.
        pass
    except Exception as e:
        print(f"DB Error: {e}")
        
def extract_title_from_body(body):
    match = re.search(r"\*\*Problem\*\*: (.*)", body)
    if match:
        return match.group(1).strip()
    return None

def main():
    prs = fetch_recent_prs(limit=200)
    print(f"Found {len(prs)} PRs.")
    
    updates_count = 0
    
    # Load JSON data first
    with open(JSON_FILE, 'r') as f:
        json_data = json.load(f)
        
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    
    for pr in prs:
        pr_number = pr['number']
        body = pr['body']
        
        title = extract_title_from_body(body)
        if not title:
            # Try to get it from PR title? "[Category] [Severity] Title"
            # pr_title = pr['title']
            # But body is more reliable if generated by our script.
            continue
            
        if title not in json_data:
            # print(f"Title not found in JSON: {title}")
            continue
            
        # Check if needs update
        current_status = json_data[title].get('pr_created', False)
        current_pr = json_data[title].get('pr_number')
        
        if not current_status or current_pr != pr_number:
            print(f"Updating {title}: PR #{pr_number}")
            
            # Update JSON
            json_data[title]['pr_created'] = True
            json_data[title]['pr_number'] = pr_number
            
            # Update DB
            cursor.execute("""
                UPDATE problems 
                SET pr_created = 1, pr_number = ?
                WHERE title = ?
            """, (pr_number, title))
            
            updates_count += 1
            
    conn.commit()
    conn.close()
    
    if updates_count > 0:
        print(f"Saving {updates_count} updates to JSON...")
        with open(JSON_FILE, 'w') as f:
            json.dump(json_data, f, indent=2)
    else:
        print("No updates needed.")

if __name__ == "__main__":
    main()
