name: Linux Stack
permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Copy env file
        run: cp sample.env .env
      - name: Build and launch stack
        run: docker compose up --build --nocache -d
      - name: Show running containers
        run: docker compose ps
      - name: Tear down stack
        if: always()
        run: docker compose down
