name: CI
on:
  workflow_dispatch: # Allows manual triggering of the workflow from the GitHub UI
  # Temporarily disabled: Comment out the 'on' section to prevent automatic runs
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install dependencies from the main requirements file
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Optionally install dependencies for individual services if they exist
          # Example: if [ -f tarpit/requirements.txt ]; then pip install -r tarpit/requirements.txt; fi
          # Example: if [ -f admin_ui/requirements.txt ]; then pip install -r admin_ui/requirements.txt; fi

      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics