name: CI

on:
  workflow_dispatch: # Allows manual triggering of the workflow from the GitHub UI
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pre-commit
          # Optionally install dependencies for individual services if they exist
          # Example: if [ -f tarpit/requirements.txt ]; then pip install -r tarpit/requirements.txt; fi
          # Example: if [ -f admin_ui/requirements.txt ]; then pip install -r admin_ui/requirements.txt; fi

      - name: Run pre-commit
        run: pre-commit run --all-files
