name: "Auto Label Pull Requests"

permissions:
  pull-requests: write

on:
  workflow_dispatch: # Allows manual triggering of the workflow from the GitHub UI
  # Uncomment the lines below to enable automatic runs on push or pull request events
  # pull_request:
  #   types: [opened, synchronize, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Label based on PR content
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
